---
ID: "4bb4ac97-7ef8-441a-baf7-baf63ae95b0a"
Parent: "debffa8b-565a-46ce-9d12-6c2a84c59011"
Template: "debffa8b-565a-46ce-9d12-6c2a84c59011"
Path: /sitecore/templates/Foundation/Glass/Models/Core Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20131114T135010
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
