---
ID: "e72ffca8-b262-4b1a-8289-b969a63a6f69"
Parent: "193b76ac-3430-4dd0-bc45-f05562d363ca"
Template: "193b76ac-3430-4dd0-bc45-f05562d363ca"
Path: /sitecore/templates/Foundation/Glass/Models/Core Data Item/__Standard Values
DB: master
SharedFields:
- ID: "a0cb3965-8884-4c7a-8815-b6b2e5ced162"
  Hint: __Editors
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20140820T232558Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ameagle
